### ISSUE TITLE
Read SVG Path and Produce iRobot commands

### ISSUE THREAD

**Issue by aroller** [LillieRoller/Sketcher#10]
in #3 irobot commands were made.
in #6 svg commands were made.
Now make the "main" `Sketcher` class that imports both `svg.path` and `irobot.codelevel3`.  Create a function `draw_path` that accepts a single svg path and call the irobot commands.   

Print the irobot commands that can be put into the irobot coding app simulator to view its behavior.  We'll stick with the square we worked on in #6.  the corresponding test:

`<path d="M 0 0 H 32 V 32 H 0 L 0 0"/>` goes into `draw_path` function.  Notice the values have been adjusted to match irobot root's standard 16cm squares provided in simulation and the physical drawing surface.  Also notice the original coordinates of 0,0 match the origin or where the robot is placed, out of simplicity. Future improvements will need to adjust to the coordinates system given.

```
await robot.navigate_to(0,0)
await robot.set_marker(Marker.DOWN)
await robot.navigate_to(32,0)
await robot.navigate_to(32,32)
await robot.navigate_to(0,32)
await robot.navigate_to(0,0)
await robot.set_marker(Marker.UP)
```
Manually recreate level 3 code at the coding app.

**Acceptance Criteria**
* Screenshot of simulator showing the commands and resulting square drawn
* Photo of the real Sketcher robot drawing the square

NOTE: This issue is to help understand the difference of the robot coordinate system vs the [SVG coordinate system](https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Positions).

![image](https://user-images.githubusercontent.com/312949/201539478-a063e260-4f48-49a2-b91c-61d801d3ac9e.png)

<img width="365" alt="image" src="https://user-images.githubusercontent.com/312949/201539468-1dc29c5c-3a81-45ee-8045-5d7bdc165c11.png">

**Comment by LillieRoller** [comment]
first attempt
```
await robot.set_marker(Marker.UP)
await robot.navigate_to(0.0,0.0)
await robot.set_marker(Marker.DOWN)
await robot.navigate_to(32.0,0.0)
await robot.set_marker(Marker.DOWN)
await robot.navigate_to(32.0,32.0)
await robot.set_marker(Marker.DOWN)
await robot.navigate_to(0.0,32.0)
await robot.set_marker(Marker.DOWN)
await robot.navigate_to(0.0,0.0)
```

**Comment by LillieRoller** [comment]
<img width="1184" alt="image" src="https://user-images.githubusercontent.com/115892189/212544746-bb2a247c-fff4-4375-befc-27eb711e100c.png">

ran the command in irobot education platform.
