### ISSUE TITLE
Create a writer to generate irobot Level 3 python commands

### ISSUE THREAD

**Issue by aroller** [LillieRoller/Sketcher#3]
Create a python class that receives commands with values to generate the python code that could navigate the robot. 

<img width="686" alt="image" src="https://user-images.githubusercontent.com/312949/200155085-78fc7062-9fc1-4a18-8786-d39839429c97.png">

irobot coding app allows an advanced level 3 programming which uses python commands to visualize what will be executed.  This will be a good way to practice algorithms that read SVG and provide commands to the robot, but without needing the robot to be connected.  

Create these commands that will be used:
* `move`
* `navigate_to`
* `set_marker` with `Marker.UP` and `Marker.DOWN`

Write tests to validate each command is provided properly by the function in `irobot.codelevel3` module.

**Comment by LillieRoller** [comment]
navigate_to done

set_marker... still needs work

**Comment by LillieRoller** [comment]
All the functions are available that we are planing to use.
